### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by MarcusCHill**
MUI Pagination is added below the fetched pet list to allow users to load a specific page of pets from the overall list. 
Max number of pages is defined by the fetched pet list.
Maintains animal type, and zip-code parameters across page change.

### CODE REVIEW

**Review by tarikutk — APPROVED** [review]
Looks Good. but I think we need to remove useEffect from zipcode since adoptPagination is hadling it better. it is also duplication.

**Review by IreneS1 — APPROVED** [review]
Looks great! Just merge conflicts I caused you haha

**Comment by mnca16** [comment]
Looks great! I would suggest redirect to top once a new page is loaded, but that can be another ticket. 

Also, I accidentally did 'git pull' on this branch, after that I used 'git reset --hard HEAD' everything seemed good but just for you to know. I hope that won't cause any issues.

**Review by mnca16 — APPROVED** [review]

**Comment by IreneS1** [comment]
An other suggesting for another ticket: when sorting, right now the page number stays the same. For example, if i'm on page two and I decide to sort, it stays on page two. We need to restart on page one. Other than that, works great!

**Review by Jay-zar — APPROVED** [review]

**Pull request merged**
