### PR TITLE
added firebase folder with firebase config file

### PR DESCRIPTION
**Pull request by mnca16**

### CODE REVIEW

**Review by MarcusCHill — COMMENTED** [review]
Hello, here are somethings I noticed with initializing firebase, when you export fireConfig you have it set to equal the firebaseConfig (const fireConfig = firebaseConfig) rather than our firebase app. This will return the object of our configuration values (apikey, authDomain, projectID, etc.), the configuration is good to set up our firebase app but we should look to export a variable that accesses firebase ( const firebaseApp = firebase ). In this case I renamed the variable from fireConfig to firebaseApp and set it equal to firebase. This will allow us to connect to the app, firestore, authentication, and other great features that firebase offers. Additionally there seems to be an extra FirebaseConfig.js file with similar content other than comments. Other than that I believe all is well!

**Comment by mnca16** [comment]
Right! Thank you for your review. There is not actually a duplicate file, I just created a folder and save the firebaseConfig file there. I thought I've changed the variable in the last commit (I did it on github).

**Review by MarcusCHill — APPROVED** [review]

**Review by IreneS1 — APPROVED** [review]
Great work Monica!

**Review by tarikutk — APPROVED** [review]
Good work.

**Pull request merged**
