### PR TITLE
added PetBio and CarouselPhoto components

### PR DESCRIPTION
**Pull request by mnca16**
Layout of the pet's bio page. 
In this PR:

- Added Pet's bio route.

- Linked PetCard to Pet's bio page. 

- Added Carousel 

- Added Pet's info (placeholder)

- Dependencies installed:

    -"react-material-ui-carousel": "^3.4.2",

### CODE REVIEW

**Comment by tarikutk** [comment]
it looks good, but for the image, we need to pass the image of the selected card. we also need to pass the object of the selected pet, then we can fill the breed, age, size and other info in the bio page.

**Comment by tarikutk** [comment]
I also see a merge conflict in the app.js

**Comment by tarikutk** [comment]
it looks good, but for the image, we need to pass the image of the selected card. we also need to pass the object of the selected pet, then we can fill the breed, age, size and other info in the bio page.

**Comment by tarikutk** [comment]
I also see a merge conflict.

**Review by IreneS1 — APPROVED** [review]
Great Job! I see you'll pass the pet info in next PR.

**Comment by mnca16** [comment]
> 

Thank you! Yes, currently working on passing the data.

**Comment by MarissaLZ** [comment]
Awesome job!

**Review by tarikutk — APPROVED** [review]

**Pull request merged**
