### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by MarcusCHill**
-Login form
-Connects Login page to routing
-Allows google auth
-Sets isLoggedIn state with Boolean value
-Sets userProfile state with user info
-Package.json changes rid warnings mentioned before with importing firebase

### CODE REVIEW

**Comment by tarikutk** [comment]
@MarcusCHill, I think we need the api keys to check how it is working. anther thing is that irene already fixed the firebase warning issue without upgrading firebase. just with this line. `import firebase from "firebase/app"
import 'firebase/firestore';`

**Comment by MarcusCHill** [comment]
@tarikutk thank you I will leave the api keys for firebase in the slack channel. Also those changes seemed to work until I had to add “import firebase/auth” in which the same warnings appeared again. I can remove this change if that’s better to allow for a different solution but the warnings will be present as the login page uses firebase authentication.

**Comment by tarikutk** [comment]
Ok. yeah. you are right. now in your case we need the firebase/auth.

**Review by tarikutk — APPROVED** [review]

**Comment by tarikutk** [comment]
lets also create a signup page and forgot password form in a new ticket.

**Review by MarissaLZ — APPROVED** [review]
The form looks great! Everything is coming together nicely

**Pull request merged**
