### PR TITLE
Feature/footer

### PR DESCRIPTION
**Pull request by Jay-zar**
I did not leave in a folder for icon images since they can be imported from MUI. Basic styling was added to Footer.js to have a cohesive shape.

### CODE REVIEW

**Comment by tarikutk** [comment]
hey @Jay-zar , This branch has conflict. pull the latest update of main branch, merge it to your branch, then resolve the conflict in vscode or any text editor you work with.

**Review by mnca16 — COMMENTED** [review]
Looks good to me! Glad you found out how to change the direction.

**Review by mnca16 — APPROVED** [review]

**Review by MarcusCHill — COMMENTED** [review]
I think the footer looks great, id suggest adding a target attribute to certain links like CTD MUI Firebase and Figma and set it to _blank so it can open in a separate tab.

**Review by tarikutk — APPROVED** [review]

**Comment by IreneS1** [comment]
Looks great. Just one thing; did we want to have the git icon along with the other icons?

**Pull request merged**
