### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by MarissaLZ**
- Moves logic in `<App/>` to the `<Adopt/>` component
- Adds empty components tp the pages folder `<Home/>`,`<Adopt/>`, `<Volunteer/>`, `<Donate/>`, and `<About/>` 
- Adds routing and links in <Navbar/>

https://user-images.githubusercontent.com/86141440/184466824-0450a416-928f-46fa-a6a7-6ef0d0aeef76.mov

### CODE REVIEW

**Review by tarikutk — CHANGES_REQUESTED** [review]
Good work. only one change is need. it is saying cannot find the folders. I think It is because of the last commit. you forgot to lowercase the folders as well. components and pages.

**Comment by MarissaLZ** [comment]
Thanks for catching that! I have fixed the folder names.

**Review by tarikutk — APPROVED** [review]

**Review by MarcusCHill — APPROVED** [review]
It looks nice, I think it would be beneficial to let the "APP NAME" serve as a link to navigate back to the home page if users wish to navigate back there.

**Comment by MarissaLZ** [comment]
Thanks! I added the link to the logo to direct to the home page

**Pull request merged**
