### PR TITLE
Create context

### PR DESCRIPTION
**Pull request by MarissaLZ**
- Creates a UserContext and PetContext
- moves the following states to the newly created contexts
` const [isLoggedIn, setIsLoggedIn] = React.useState(false)`
`  const [userProfile, setUserProfile] = React.useState([])`
` const [petList, setPetList] = React.useState([])` 
`const [isFavoritedList, setIsFavoritedList] = React.useState([])`

*Note after looking at the files it made sense to include `isFavoritedList` in a context. It will be easier to use for the favorites page.

I tested the login page and the favorites icon, and everything appear to be still successfully connecting to Firebase

### CODE REVIEW

**Review by MarcusCHill — COMMENTED** [review]
Each import statement to the context.js file in App, PetList, ZipCodeInput, and Login, has "Context" capitalized causing an error. Other than that it looks good! Also, beware of a merger conflict with Login.js.

**Review by mnca16 — COMMENTED** [review]
Encountered the same issue with the import files, but it looks great. Can't wait to use context.

**Comment by MarissaLZ** [comment]
Fixed the merge conflicts. I need to start watching that my import statements are getting updated when I change a file name.

**Review by tarikutk — APPROVED** [review]

**Comment by tarikutk** [comment]
sorry. that was by mistake that I closed the pull request, but reopened it again.

**Comment by tarikutk** [comment]
that is a Good work.

**Review by MarcusCHill — APPROVED** [review]

**Pull request merged**
